name: Upload artifact file

on:
  push:
    branches:
      - test-pr-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install project
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Bundle project
        run: zip -r --junk-paths bundle.zip lib/
      - name: Archive bundle.zip
        uses: actions/upload-artifact@v2
        with:
          name: bundle.zip
          path: bundle.zip
