name: Upload artifact file

on:
  push:
    branches:
      - test-pr-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install project
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Get version of package.json
        id: version
        run: |
          VERSION=`cat package.json | jq -r .version`
          echo "::set-output name=VERSION::$VERSION"
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: output_${{steps.version.outputs.VERSION}}.zip
          path: ./lib
      - name: Create commits
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          date +%s > date.txt
          git add -A
          git commit -m "dummy commit"
      - name: Get workflow url
        id: workflow
        run: echo "::set-output name=WORKFLOW_URL::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: test pull request
          branch: upload_artifact_file/${{steps.version.outputs.VERSION}}
          body: |
            Workflow URL:
            - ${{ steps.workflow.outputs.WORKFLOW_URL }}
          delete-branch: true
