name: Upload artifact file

on:
  push:
    branches:
      - test-pr-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install project
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Archive bundle.zip
        uses: actions/upload-artifact@v2
        with:
          name: bundle.zip
          path: ./lib
      - name: Create commits
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          date +%s > date.txt
          git add -A
          git commit -m "dummy commit"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        env:
          WORKFLOW_URL: ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}
        with:
          title: test pull request
          body: |
            Workflow URL:
            - ${{ env.WORKFLOW_URL }}
          delete-branch: true

